apiVersion: v1
kind: Service
metadata:
  name: schema-reg
  namespace: kafka
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: schema-reg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-reg
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-reg
  template:
    metadata:
      labels:
        app: schema-reg
    spec:
      containers:
        - name: schema-reg
          image: confluentinc/cp-schema-registry:5.3.2
          ports:
            - containerPort: 8090
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: strimzi-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemareg
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8090
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 3Gi          
  
            # k exec -it nombre-pod -- nslookup
