apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  namespace: kafka
  name: uinput-topic
  labels:
    strimzi.io/cluster: strimzi-kafka-cluster
spec:
  replicas: 3
  partitions: 10

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  namespace: kafka
  name: file-events-topic
  labels:
    strimzi.io/cluster: strimzi-kafka-cluster
spec:
  replicas: 3
  partitions: 10
